### ISSUE TITLE
Naming convention for filter classes

### ISSUE THREAD

**Issue by jorainer** [Bioconductor/AnnotationFilter#1]
@mtmorgan from your code I understand that the filter class names will be CamelCase always, replacing any `_` in the field name with an Upper case letter (e.g. `gene_id` will be `GeneIdFilter`).

Just wanted to confirm that this will be the standard naming convention - because then I have to adapt `ensembldb` later, since there I just replaced the `_` and did not make the next character upper case.

**Comment by mtmorgan** [comment]
I like the idea of replacing `_i` with `I`; the snake I guess was somehow a delimiter and now we're delimiting with camel case. But I could be swayed; I'll let you close the issue with your preference, and will adapt...

**Comment by jorainer** [comment]
OK, let's stick to your `_i` to `I` replacement. Fine for me. 
I was anyway not completely happy with the inconsistent camel casing I had in `ensembldb` - now it's a good time to change that.
