### ISSUE TITLE
Use lazyeval to translate query expression into filter objects

### ISSUE THREAD

**Issue by jorainer** [Bioconductor/AnnotationFilter#16]
I was integrating the `AnnotationFilter` package into `ensembldb` and stumbled over some problems, especially regarding the currently implemented lazy evaluation.

I would like to change that to `lazyeval` based evaluation (similar to `GenomicDataCommons`): filter expressions will then be `~ gene_id == "BCL2"` and for lazy evaluation we would use `f_eval`.

Also, I would like to use a shorter and better name for  `convertFilterExpression`. Since the function is translating a filter query into an `AnnotationFilter` (or `AnnotationFilterList`) I thought we could name the function `AnnotationFilter`. Calling `AnnotationFilter(~ gene_id == "BCL2")` would e.g. create a `GeneIdFilter` with the specified value.

@mtmorgan, what do you think?

**Comment by mtmorgan** [comment]
sounds ok to me
