### ISSUE TITLE
Export AnnotationFilter class

### ISSUE THREAD

**Issue by jorainer** [Bioconductor/AnnotationFilter#2]
Exporting the `AnnotationFilter` class allows new filters to be created in other packages. So, not all filter objects need to be necessarily defined in `AnnotationFilters`.

**Comment by mtmorgan** [comment]
Just on the setters, I wonder whether we really want these? From the user perspective it seems like it's easy just to create a new 'read only' instance? This is just a sense, and if there's a reasonable use case in for setters then I'm ok with that.

**Comment by jorainer** [comment]
Good point. I just put the setters so that users don't start setting the slot value directly with `x@value <- 4` since then there would be no control whether the object is still valid.

**Comment by jorainer** [comment]
Removed the setter methods.
