### ISSUE TITLE
Small inconsistent class naming

### ISSUE THREAD

**Issue by hpages** [Bioconductor/AnnotationFilter#22]
Hi guys,

Any chance the `GenenameFilter` class could be renamed `GeneNameFilter` to be consistent with what seems to be the naming scheme adopted for other classes like `TxNameFilter`, `ExonNameFilter`, `SeqNameFilter`? Note that `SeqNameFilter` would actually be a better candidate if there must be an exception to the rule ;-)

Thanks,
H.

**Comment by jorainer** [comment]
That's a little short notice before the Bioconductor release. Honestly, I'd really like to rename it to `GeneNameFilter`, also since the name of the database column in `EnsDb` is `gene_name`.

**Comment by hpages** [comment]
Could be done after the release (in devel of course), with proper deprecation/defunct cycle for the `GenenameFilter()` constructor.

Also any particular reason why the filter for gene symbols was named `SymbolFilter` and not `GeneSymbolFilter`? All other filters on some gene attribute are named `GeneSomthingFilter` e.g. `GeneIdFilter`, `GenenameFilter`, `GeneBiotypeFilter`, etc...

Thanks!

**Comment by hpages** [comment]
Hi @jotsetung -- any chance this renaming could happen this devel cycle? Thanks!

**Comment by jorainer** [comment]
Has been merged into master. I'm closing now.

**Comment by hpages** [comment]
Thanks @jotsetung ! Do you think you can also push this change to git.bioconductor.org? That way the build system will pick it up and the change will propagate to BioC 3.8. Thanks!

**Comment by jorainer** [comment]
I pushed to bioconductor - thought Martin did that already. Sorry for the delays on this issue!

**Comment by hpages** [comment]
Excellent. Thanks!
