### ISSUE TITLE
Supported Filter classes

### ISSUE THREAD

**Issue by jorainer** [Bioconductor/AnnotationFilter#4]
I was wondering, are we going to provide all possible filters or *just* a selection of the most common filters.

I would suggest the following filters (also thinking of what I need/use in `ensembldb`):
+ `GeneIdFilter`
+ `GeneNameFilter`
+ `SymbolFilter`
+ `TxIdFilter`
+ `TxNameFilter`
+ `ExonIdFilter`
+ `ExonRankFilter`
+ `ProteinIdFilter`
+ `UniprotIdFilter`

Now, in my case these would correspond to Ensembl gene IDs etc - I just find e.g. `EnsembldGeneIdFilter` a little long to type, that's why I would opt for the shorter, more general names (`GeneIdFilter`).

**Comment by mtmorgan** [comment]
Let's start with the filters defined above, so added to the appropriate `.CHAR_FIELDS` and `.INT_FIELDS`. 

I think it would be fun to figure out how a package like ensembldb could call in to AnnotationFilters to create a class 'on the fly' and register it, so that when Organism.dply came along it could make the same call and get the class already defined by ensembldb.

**Comment by jorainer** [comment]
Now, what puzzles me a little is that in `Organisms.dplyr` the `ExonRankFilter` is a `character`-based filter. I did add it as a `integer`-based filter since it's supposed to provide the index/rank of the exon within the transcript.

**Comment by mtmorgan** [comment]
yes, I think it should be integer-based. Also the `*IdFilter` filters in Organism.dplyr seem like they should be integer-based.

**Comment by jorainer** [comment]
Hm, that's not ideal - integer-based filters support conditions `>`, `>=` etc which does not really make much sense for an ID. In `ensembldb` the IDs are characters. I would rather like to keep them as `character` filters. 

In `ensembldb` I'm using a function to access the value of the filter formatted for the SQL call:
```r
.valueForEnsDb <- function(x) {
    vals <- unique(x@value)
    if (x@.valueIsCharacter) {
        vals <- sQuote(gsub(unique(vals), pattern = "'", replacement = "''"))
    }
    if (length(vals) > 1)
        vals <- paste0("(",  paste0(vals, collapse = ","), ")")
    ## Process the like/startsWith/endsWith
    if (condition(x) == "startsWith")
        vals <- paste0("'", unique(x@value), "%'")
    if (condition(x) == "endsWith")
        vals <- paste0("'%", unique(x@value), "'")
    return(vals)
}
```

In `Organism.dplyr` one could use a method instead for the `*IdFilter` (or at least for some of them) that returns the value of the filter as an `integer`.

**Comment by mtmorgan** [comment]
OK the IDs can be treated as character for the purpose of filtering.

**Comment by jorainer** [comment]
Closing this issue now.
