### ISSUE TITLE
supportedFilters method

### ISSUE THREAD

**Issue by jorainer** [Bioconductor/AnnotationFilter#6]
What about adding a `supportedFilters` method (instead of the currently used function) that dispatches on a parameter `x`. If `x = "missing"` it calls the standard function, but for e.g. `x = "EnsDb"` it lists all filters that are supported for a `EnsDb` (this method for `EnsDb` would have to be defined in and exported from `ensembldb`).

**Comment by mtmorgan** [comment]
sounds good to me.
