### ISSUE TITLE
AnnotationFilters also providing additional functionality besides classes?

### ISSUE THREAD

**Issue by jorainer** [Bioconductor/AnnotationFilter#8]
I was wondering whether `AnnotationFilters` should *just* provide a basic set of filter objects and leave all further implementations (how they *act*) to the packages using them, or if `AnnotationFilters` should also provide basic filtering concepts.

**Comment by mtmorgan** [comment]
What functionality you're thinking of? Logic for combining filters?

**Comment by jorainer** [comment]
Just some simple logic, like *translating* a filter to a `character` representing the respective part of the SQL call.

**Comment by mtmorgan** [comment]
Sounds ok. One thing I liked about Organism.dplyr was the way it uses inst/schema to store SQL chunks; ideally , the R code doesn't actually contain any SQL strings. For instance https://github.com/Bioconductor/Organism.dplyr/blob/master/R/src.R#L191-L201

**Comment by jorainer** [comment]
Another thing - would be nice to be able to do something like `filter(edb, gene_id == "something" & seq_name == "X")` with `edb` being an `EnsDb` and the conditions being translated into the SQL call.

Do you know where I could start looking for an elegant way to parse the condition or extract its elements?

**Comment by jorainer** [comment]
Thinking it over I would rather implement first a way to combine multiple filters (with *and* or *or*; new issue #11) and leave the functionality to *translate* (or interpret) the filters to the packages using them (like `Organism.dplyr` or `ensembldb`) since that will be specific to the data the package provides

**Comment by mtmorgan** [comment]
Yes for leaving interpretation to packages doing implementation. This discussion might be an interesting starting point for elegant solutions https://github.com/Bioconductor/GenomicDataCommons/issues/16 .

**Comment by jorainer** [comment]
Closing this because picked up by issues #11 and #12
